################################################################
# Entrypoints configuration
################################################################

defaultEntryPoints = ["http", "https"]
[entryPoints]
    [entryPoints.http]
    address = ":8228"

[api]
    entryPoint = "http"
    dashboard = true

[file]

[frontends]
    [frontends.usermanagement]
		entrypoints = ["http"]		
		backend="usermanagement"
		[frontends.usermanagement.routes.matchUrl]
			rule="PathPrefixStrip:/api.usermanagement"

[backends]
    [backends.usermanagement]
        [backends.usermanagement.servers.main1]
			url = "http://107.113.53.47:9001"
			weight = 3

		[backends.usermanagement.servers.main2]
			url = "http://107.113.53.47:9002"
			weight = 5

# Try: 
#	http://localhost:8228/api.usermanagement <-> http://107.113.53.47:9001
#	http://localhost:8228/api.usermanagement/api/v1/tasks <-> http://107.113.53.47:9001

################################################################
# Traefik logs configuration
################################################################

[traefikLog]
filePath = "logs/traefik.log"
